# To execute this docker-compose yml file use `docker-compose -f docker-compose-grid.yml up -d`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-grid.yml down`
# To run standalone>> docker run -d -p 4444:4444 --shm-size=2g seleniarm/standalone-chromium:latest

version: "3"
services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium-network

  chrome:
    image: seleniarm/node-chromium:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    networks:
      - selenium-network
    volumes:
      - ./shared:/shared


  chrome2:
    image: seleniarm/node-chromium:latest
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2gb
    networks:
      - selenium-network
    volumes:
      - ./shared:/shared

networks:
  selenium-network:
    external: true
